package com.example.administrator.gamedemo.utils;

import android.content.Context;

import com.example.administrator.gamedemo.R;

import java.util.ArrayList;
import java.util.List;

/**
 * @auther lixu
 * Created by lixu on 2017/1/11 0011.
 */
public class TopicUtil {

    public static List<String[]> initDate_MXWJ(Context mContext){
        List<String[]> answers = new ArrayList<>();
        String[] a1 = mContext.getResources().getStringArray(R.array.as_mxwj_1);
        String[] a2 = mContext.getResources().getStringArray(R.array.as_mxwj_2);
        String[] a3 = mContext.getResources().getStringArray(R.array.as_mxwj_3);
        String[] a4 = mContext.getResources().getStringArray(R.array.as_mxwj_4);
        String[] a5 = mContext.getResources().getStringArray(R.array.as_mxwj_5);
        String[] a6 = mContext.getResources().getStringArray(R.array.as_mxwj_6);
        String[] a7 = mContext.getResources().getStringArray(R.array.as_mxwj_7);
        String[] a8 = mContext.getResources().getStringArray(R.array.as_mxwj_8);
        String[] a9 = mContext.getResources().getStringArray(R.array.as_mxwj_9);
        String[] a10 = mContext.getResources().getStringArray(R.array.as_mxwj_10);
        String[] a11 = mContext.getResources().getStringArray(R.array.as_mxwj_11);
        String[] a12 = mContext.getResources().getStringArray(R.array.as_mxwj_12);
        String[] a13 = mContext.getResources().getStringArray(R.array.as_mxwj_13);
        String[] a14 = mContext.getResources().getStringArray(R.array.as_mxwj_14);
        String[] a15 = mContext.getResources().getStringArray(R.array.as_mxwj_15);
        String[] a16 = mContext.getResources().getStringArray(R.array.as_mxwj_16);
        String[] a17 = mContext.getResources().getStringArray(R.array.as_mxwj_17);
        String[] a18 = mContext.getResources().getStringArray(R.array.as_mxwj_18);
        String[] a19 = mContext.getResources().getStringArray(R.array.as_mxwj_19);
        String[] a20 = mContext.getResources().getStringArray(R.array.as_mxwj_20);
        String[] a21 = mContext.getResources().getStringArray(R.array.as_mxwj_21);
        String[] a22 = mContext.getResources().getStringArray(R.array.as_mxwj_22);
        String[] a23 = mContext.getResources().getStringArray(R.array.as_mxwj_23);
        String[] a24 = mContext.getResources().getStringArray(R.array.as_mxwj_24);
        String[] a25 = mContext.getResources().getStringArray(R.array.as_mxwj_25);
        String[] a26 = mContext.getResources().getStringArray(R.array.as_mxwj_26);
        String[] a27 = mContext.getResources().getStringArray(R.array.as_mxwj_27);
        String[] a28 = mContext.getResources().getStringArray(R.array.as_mxwj_28);
        String[] a29 = mContext.getResources().getStringArray(R.array.as_mxwj_29);
        String[] a30 = mContext.getResources().getStringArray(R.array.as_mxwj_30);
        String[] a31 = mContext.getResources().getStringArray(R.array.as_mxwj_31);
        String[] a32 = mContext.getResources().getStringArray(R.array.as_mxwj_32);
        String[] a33 = mContext.getResources().getStringArray(R.array.as_mxwj_33);
        String[] a34 = mContext.getResources().getStringArray(R.array.as_mxwj_34);
        String[] a35 = mContext.getResources().getStringArray(R.array.as_mxwj_35);
        String[] a36 = mContext.getResources().getStringArray(R.array.as_mxwj_36);
        String[] a37 = mContext.getResources().getStringArray(R.array.as_mxwj_37);
        String[] a38 = mContext.getResources().getStringArray(R.array.as_mxwj_38);
        String[] a39 = mContext.getResources().getStringArray(R.array.as_mxwj_39);
        String[] a40 = mContext.getResources().getStringArray(R.array.as_mxwj_40);
        String[] a41 = mContext.getResources().getStringArray(R.array.as_mxwj_41);
        String[] a42 = mContext.getResources().getStringArray(R.array.as_mxwj_42);
        String[] a43 = mContext.getResources().getStringArray(R.array.as_mxwj_43);
        String[] a44 = mContext.getResources().getStringArray(R.array.as_mxwj_44);
        String[] a45 = mContext.getResources().getStringArray(R.array.as_mxwj_45);
        String[] a46 = mContext.getResources().getStringArray(R.array.as_mxwj_46);
        String[] a47 = mContext.getResources().getStringArray(R.array.as_mxwj_47);
        String[] a48 = mContext.getResources().getStringArray(R.array.as_mxwj_48);
        String[] a49 = mContext.getResources().getStringArray(R.array.as_mxwj_49);
        String[] a50 = mContext.getResources().getStringArray(R.array.as_mxwj_50);
        String[] a51 = mContext.getResources().getStringArray(R.array.as_mxwj_51);
        String[] a52 = mContext.getResources().getStringArray(R.array.as_mxwj_52);
        String[] a53 = mContext.getResources().getStringArray(R.array.as_mxwj_53);
        String[] a54 = mContext.getResources().getStringArray(R.array.as_mxwj_54);
        String[] a55 = mContext.getResources().getStringArray(R.array.as_mxwj_55);
        String[] a56 = mContext.getResources().getStringArray(R.array.as_mxwj_56);
        String[] a57 = mContext.getResources().getStringArray(R.array.as_mxwj_57);
        String[] a58 = mContext.getResources().getStringArray(R.array.as_mxwj_58);
        String[] a59 = mContext.getResources().getStringArray(R.array.as_mxwj_59);
        String[] a60 = mContext.getResources().getStringArray(R.array.as_mxwj_60);
        String[] a61 = mContext.getResources().getStringArray(R.array.as_mxwj_61);
        String[] a62 = mContext.getResources().getStringArray(R.array.as_mxwj_62);
        String[] a63 = mContext.getResources().getStringArray(R.array.as_mxwj_63);
        String[] a64 = mContext.getResources().getStringArray(R.array.as_mxwj_64);
        String[] a65 = mContext.getResources().getStringArray(R.array.as_mxwj_65);
        String[] a66 = mContext.getResources().getStringArray(R.array.as_mxwj_66);
        String[] a67 = mContext.getResources().getStringArray(R.array.as_mxwj_67);
        String[] a68 = mContext.getResources().getStringArray(R.array.as_mxwj_68);
        String[] a69 = mContext.getResources().getStringArray(R.array.as_mxwj_69);
        String[] a70 = mContext.getResources().getStringArray(R.array.as_mxwj_70);
        String[] a71 = mContext.getResources().getStringArray(R.array.as_mxwj_71);
        String[] a72 = mContext.getResources().getStringArray(R.array.as_mxwj_72);
        String[] a73 = mContext.getResources().getStringArray(R.array.as_mxwj_73);
        String[] a74 = mContext.getResources().getStringArray(R.array.as_mxwj_74);
        String[] a75 = mContext.getResources().getStringArray(R.array.as_mxwj_75);
        String[] a76 = mContext.getResources().getStringArray(R.array.as_mxwj_76);
        String[] a77 = mContext.getResources().getStringArray(R.array.as_mxwj_77);
        String[] a78 = mContext.getResources().getStringArray(R.array.as_mxwj_78);
        String[] a79 = mContext.getResources().getStringArray(R.array.as_mxwj_79);
        String[] a80 = mContext.getResources().getStringArray(R.array.as_mxwj_80);
        String[] a81 = mContext.getResources().getStringArray(R.array.as_mxwj_81);
        String[] a82 = mContext.getResources().getStringArray(R.array.as_mxwj_82);
        String[] a83 = mContext.getResources().getStringArray(R.array.as_mxwj_83);
        String[] a84 = mContext.getResources().getStringArray(R.array.as_mxwj_84);
        String[] a85 = mContext.getResources().getStringArray(R.array.as_mxwj_85);
        String[] a86 = mContext.getResources().getStringArray(R.array.as_mxwj_86);
        String[] a87 = mContext.getResources().getStringArray(R.array.as_mxwj_87);
        String[] a88 = mContext.getResources().getStringArray(R.array.as_mxwj_88);
        String[] a89 = mContext.getResources().getStringArray(R.array.as_mxwj_89);
        String[] a90 = mContext.getResources().getStringArray(R.array.as_mxwj_90);
        String[] a91 = mContext.getResources().getStringArray(R.array.as_mxwj_91);
        String[] a92 = mContext.getResources().getStringArray(R.array.as_mxwj_92);
        String[] a93 = mContext.getResources().getStringArray(R.array.as_mxwj_93);
        String[] a94 = mContext.getResources().getStringArray(R.array.as_mxwj_94);
        String[] a95 = mContext.getResources().getStringArray(R.array.as_mxwj_95);
        String[] a96 = mContext.getResources().getStringArray(R.array.as_mxwj_96);
        String[] a97 = mContext.getResources().getStringArray(R.array.as_mxwj_97);
        String[] a98 = mContext.getResources().getStringArray(R.array.as_mxwj_98);
        String[] a99 = mContext.getResources().getStringArray(R.array.as_mxwj_99);
        String[] a100 = mContext.getResources().getStringArray(R.array.as_mxwj_100);
        String[] a101 = mContext.getResources().getStringArray(R.array.as_mxwj_101);
        String[] a102 = mContext.getResources().getStringArray(R.array.as_mxwj_102);
        String[] a103 = mContext.getResources().getStringArray(R.array.as_mxwj_103);
        String[] a104 = mContext.getResources().getStringArray(R.array.as_mxwj_104);
        String[] a105 = mContext.getResources().getStringArray(R.array.as_mxwj_105);
        String[] a106 = mContext.getResources().getStringArray(R.array.as_mxwj_106);
        String[] a107 = mContext.getResources().getStringArray(R.array.as_mxwj_107);
        answers.add(a1);
        answers.add(a2);
        answers.add(a3);
        answers.add(a4);
        answers.add(a5);
        answers.add(a6);
        answers.add(a7);
        answers.add(a8);
        answers.add(a9);
        answers.add(a10);
        answers.add(a11);
        answers.add(a12);
        answers.add(a13);
        answers.add(a14);
        answers.add(a15);
        answers.add(a16);
        answers.add(a17);
        answers.add(a18);
        answers.add(a19);
        answers.add(a20);
        answers.add(a21);
        answers.add(a22);
        answers.add(a23);
        answers.add(a24);
        answers.add(a25);
        answers.add(a26);
        answers.add(a27);
        answers.add(a28);
        answers.add(a29);
        answers.add(a30);
        answers.add(a31);
        answers.add(a32);
        answers.add(a33);
        answers.add(a34);
        answers.add(a35);
        answers.add(a36);
        answers.add(a37);
        answers.add(a38);
        answers.add(a39);
        answers.add(a40);
        answers.add(a41);
        answers.add(a42);
        answers.add(a43);
        answers.add(a44);
        answers.add(a45);
        answers.add(a46);
        answers.add(a47);
        answers.add(a48);
        answers.add(a49);
        answers.add(a50);
        answers.add(a51);
        answers.add(a52);
        answers.add(a53);
        answers.add(a54);
        answers.add(a55);
        answers.add(a56);
        answers.add(a57);
        answers.add(a58);
        answers.add(a59);
        answers.add(a60);
        answers.add(a61);
        answers.add(a62);
        answers.add(a63);
        answers.add(a64);
        answers.add(a65);
        answers.add(a66);
        answers.add(a67);
        answers.add(a68);
        answers.add(a69);
        answers.add(a70);
        answers.add(a71);
        answers.add(a72);
        answers.add(a73);
        answers.add(a74);
        answers.add(a75);
        answers.add(a76);
        answers.add(a77);
        answers.add(a78);
        answers.add(a79);
        answers.add(a80);
        answers.add(a81);
        answers.add(a82);
        answers.add(a83);
        answers.add(a84);
        answers.add(a85);
        answers.add(a86);
        answers.add(a87);
        answers.add(a88);
        answers.add(a89);
        answers.add(a90);
        answers.add(a91);
        answers.add(a92);
        answers.add(a93);
        answers.add(a94);
        answers.add(a95);
        answers.add(a96);
        answers.add(a97);
        answers.add(a98);
        answers.add(a99);
        answers.add(a100);
        answers.add(a101);
        answers.add(a102);
        answers.add(a103);
        answers.add(a104);
        answers.add(a105);
        answers.add(a106);
        answers.add(a107);
        return answers;
    }
    public static List<String[]>  initDate_LSSG(Context mContext){
        List<String[]> answers = new ArrayList<>();
        String[] a1 = mContext.getResources().getStringArray(R.array.as_lssg_1);
        String[] a2 = mContext.getResources().getStringArray(R.array.as_lssg_2);
        String[] a3 = mContext.getResources().getStringArray(R.array.as_lssg_3);
        String[] a4 = mContext.getResources().getStringArray(R.array.as_lssg_4);
        String[] a5 = mContext.getResources().getStringArray(R.array.as_lssg_5);
        String[] a6 = mContext.getResources().getStringArray(R.array.as_lssg_6);
        String[] a7 = mContext.getResources().getStringArray(R.array.as_lssg_7);
        String[] a8 = mContext.getResources().getStringArray(R.array.as_lssg_8);
        String[] a9 = mContext.getResources().getStringArray(R.array.as_lssg_9);
        String[] a10 = mContext.getResources().getStringArray(R.array.as_lssg_10);
        String[] a11 = mContext.getResources().getStringArray(R.array.as_lssg_11);
        String[] a12 = mContext.getResources().getStringArray(R.array.as_lssg_12);
        String[] a13 = mContext.getResources().getStringArray(R.array.as_lssg_13);
        String[] a14 = mContext.getResources().getStringArray(R.array.as_lssg_14);
        String[] a15 = mContext.getResources().getStringArray(R.array.as_lssg_15);
        String[] a16 = mContext.getResources().getStringArray(R.array.as_lssg_16);
        String[] a17 = mContext.getResources().getStringArray(R.array.as_lssg_17);
        String[] a18 = mContext.getResources().getStringArray(R.array.as_lssg_18);
        String[] a19 = mContext.getResources().getStringArray(R.array.as_lssg_19);
        String[] a20 = mContext.getResources().getStringArray(R.array.as_lssg_20);
        String[] a21 = mContext.getResources().getStringArray(R.array.as_lssg_21);
        String[] a22 = mContext.getResources().getStringArray(R.array.as_lssg_22);
        String[] a23 = mContext.getResources().getStringArray(R.array.as_lssg_23);
        String[] a24 = mContext.getResources().getStringArray(R.array.as_lssg_24);
        String[] a25 = mContext.getResources().getStringArray(R.array.as_lssg_25);
        String[] a26 = mContext.getResources().getStringArray(R.array.as_lssg_26);
        String[] a27 = mContext.getResources().getStringArray(R.array.as_lssg_27);
        String[] a28 = mContext.getResources().getStringArray(R.array.as_lssg_28);
        String[] a29 = mContext.getResources().getStringArray(R.array.as_lssg_29);
        String[] a30 = mContext.getResources().getStringArray(R.array.as_lssg_30);
        String[] a31 = mContext.getResources().getStringArray(R.array.as_lssg_31);
        String[] a32 = mContext.getResources().getStringArray(R.array.as_lssg_32);
        String[] a33 = mContext.getResources().getStringArray(R.array.as_lssg_33);
        String[] a34 = mContext.getResources().getStringArray(R.array.as_lssg_34);
        String[] a35 = mContext.getResources().getStringArray(R.array.as_lssg_35);
        String[] a36 = mContext.getResources().getStringArray(R.array.as_lssg_36);
        String[] a37 = mContext.getResources().getStringArray(R.array.as_lssg_37);
        String[] a38 = mContext.getResources().getStringArray(R.array.as_lssg_38);
        String[] a39 = mContext.getResources().getStringArray(R.array.as_lssg_39);
        String[] a40 = mContext.getResources().getStringArray(R.array.as_lssg_40);
        String[] a41 = mContext.getResources().getStringArray(R.array.as_lssg_41);
        String[] a42 = mContext.getResources().getStringArray(R.array.as_lssg_42);
        String[] a43 = mContext.getResources().getStringArray(R.array.as_lssg_43);
        String[] a44 = mContext.getResources().getStringArray(R.array.as_lssg_44);
        String[] a45 = mContext.getResources().getStringArray(R.array.as_lssg_45);
        String[] a46 = mContext.getResources().getStringArray(R.array.as_lssg_46);
        String[] a47 = mContext.getResources().getStringArray(R.array.as_lssg_47);
        String[] a48 = mContext.getResources().getStringArray(R.array.as_lssg_48);
        String[] a49 = mContext.getResources().getStringArray(R.array.as_lssg_49);
        String[] a50 = mContext.getResources().getStringArray(R.array.as_lssg_50);
        String[] a51 = mContext.getResources().getStringArray(R.array.as_lssg_51);
        String[] a52 = mContext.getResources().getStringArray(R.array.as_lssg_52);
        String[] a53 = mContext.getResources().getStringArray(R.array.as_lssg_53);
        String[] a54 = mContext.getResources().getStringArray(R.array.as_lssg_54);
        String[] a55 = mContext.getResources().getStringArray(R.array.as_lssg_55);
        String[] a56 = mContext.getResources().getStringArray(R.array.as_lssg_56);
        String[] a57 = mContext.getResources().getStringArray(R.array.as_lssg_57);
        String[] a58 = mContext.getResources().getStringArray(R.array.as_lssg_58);
        String[] a59 = mContext.getResources().getStringArray(R.array.as_lssg_59);
        String[] a60 = mContext.getResources().getStringArray(R.array.as_lssg_60);
        String[] a61 = mContext.getResources().getStringArray(R.array.as_lssg_61);
        String[] a62 = mContext.getResources().getStringArray(R.array.as_lssg_62);
        String[] a63 = mContext.getResources().getStringArray(R.array.as_lssg_63);
        String[] a64 = mContext.getResources().getStringArray(R.array.as_lssg_64);
        String[] a65 = mContext.getResources().getStringArray(R.array.as_lssg_65);
        String[] a66 = mContext.getResources().getStringArray(R.array.as_lssg_66);
        String[] a67 = mContext.getResources().getStringArray(R.array.as_lssg_67);
        String[] a68 = mContext.getResources().getStringArray(R.array.as_lssg_68);
        String[] a69 = mContext.getResources().getStringArray(R.array.as_lssg_69);
        String[] a70 = mContext.getResources().getStringArray(R.array.as_lssg_70);
        String[] a71 = mContext.getResources().getStringArray(R.array.as_lssg_71);
        String[] a72 = mContext.getResources().getStringArray(R.array.as_lssg_72);
        String[] a73 = mContext.getResources().getStringArray(R.array.as_lssg_73);
        String[] a74 = mContext.getResources().getStringArray(R.array.as_lssg_74);
        String[] a75 = mContext.getResources().getStringArray(R.array.as_lssg_75);
        String[] a76 = mContext.getResources().getStringArray(R.array.as_lssg_76);
        String[] a77 = mContext.getResources().getStringArray(R.array.as_lssg_77);
        String[] a78 = mContext.getResources().getStringArray(R.array.as_lssg_78);
        String[] a79 = mContext.getResources().getStringArray(R.array.as_lssg_79);
        String[] a80 = mContext.getResources().getStringArray(R.array.as_lssg_80);
        String[] a81 = mContext.getResources().getStringArray(R.array.as_lssg_81);
        String[] a82 = mContext.getResources().getStringArray(R.array.as_lssg_82);
        String[] a83 = mContext.getResources().getStringArray(R.array.as_lssg_83);
        String[] a84 = mContext.getResources().getStringArray(R.array.as_lssg_84);
        String[] a85 = mContext.getResources().getStringArray(R.array.as_lssg_85);
        String[] a86 = mContext.getResources().getStringArray(R.array.as_lssg_86);
        String[] a87 = mContext.getResources().getStringArray(R.array.as_lssg_87);
        String[] a88 = mContext.getResources().getStringArray(R.array.as_lssg_88);
        String[] a89 = mContext.getResources().getStringArray(R.array.as_lssg_89);
        String[] a90 = mContext.getResources().getStringArray(R.array.as_lssg_90);
        String[] a91 = mContext.getResources().getStringArray(R.array.as_lssg_91);
        String[] a92 = mContext.getResources().getStringArray(R.array.as_lssg_92);
        String[] a93 = mContext.getResources().getStringArray(R.array.as_lssg_93);
        String[] a94 = mContext.getResources().getStringArray(R.array.as_lssg_94);
        String[] a95 = mContext.getResources().getStringArray(R.array.as_lssg_95);
        String[] a96 = mContext.getResources().getStringArray(R.array.as_lssg_96);
        String[] a97 = mContext.getResources().getStringArray(R.array.as_lssg_97);
        String[] a98 = mContext.getResources().getStringArray(R.array.as_lssg_98);
        String[] a99 = mContext.getResources().getStringArray(R.array.as_lssg_99);
        String[] a100 = mContext.getResources().getStringArray(R.array.as_lssg_100);
        String[] a101 = mContext.getResources().getStringArray(R.array.as_lssg_101);
        String[] a102 = mContext.getResources().getStringArray(R.array.as_lssg_102);
        String[] a103 = mContext.getResources().getStringArray(R.array.as_lssg_103);
        String[] a104 = mContext.getResources().getStringArray(R.array.as_lssg_104);
        String[] a105 = mContext.getResources().getStringArray(R.array.as_lssg_105);
        String[] a106 = mContext.getResources().getStringArray(R.array.as_lssg_106);
        String[] a107 = mContext.getResources().getStringArray(R.array.as_lssg_107);
        String[] a108 = mContext.getResources().getStringArray(R.array.as_lssg_108);
        String[] a109 = mContext.getResources().getStringArray(R.array.as_lssg_109);
        String[] a110 = mContext.getResources().getStringArray(R.array.as_lssg_110);
        String[] a111 = mContext.getResources().getStringArray(R.array.as_lssg_111);
        String[] a112 = mContext.getResources().getStringArray(R.array.as_lssg_112);
        answers.add(a1);
        answers.add(a2);
        answers.add(a3);
        answers.add(a4);
        answers.add(a5);
        answers.add(a6);
        answers.add(a7);
        answers.add(a8);
        answers.add(a9);
        answers.add(a10);
        answers.add(a11);
        answers.add(a12);
        answers.add(a13);
        answers.add(a14);
        answers.add(a15);
        answers.add(a16);
        answers.add(a17);
        answers.add(a18);
        answers.add(a19);
        answers.add(a20);
        answers.add(a21);
        answers.add(a22);
        answers.add(a23);
        answers.add(a24);
        answers.add(a25);
        answers.add(a26);
        answers.add(a27);
        answers.add(a28);
        answers.add(a29);
        answers.add(a30);
        answers.add(a31);
        answers.add(a32);
        answers.add(a33);
        answers.add(a34);
        answers.add(a35);
        answers.add(a36);
        answers.add(a37);
        answers.add(a38);
        answers.add(a39);
        answers.add(a40);
        answers.add(a41);
        answers.add(a42);
        answers.add(a43);
        answers.add(a44);
        answers.add(a45);
        answers.add(a46);
        answers.add(a47);
        answers.add(a48);
        answers.add(a49);
        answers.add(a50);
        answers.add(a51);
        answers.add(a52);
        answers.add(a53);
        answers.add(a54);
        answers.add(a55);
        answers.add(a56);
        answers.add(a57);
        answers.add(a58);
        answers.add(a59);
        answers.add(a60);
        answers.add(a61);
        answers.add(a62);
        answers.add(a63);
        answers.add(a64);
        answers.add(a65);
        answers.add(a66);
        answers.add(a67);
        answers.add(a68);
        answers.add(a69);
        answers.add(a70);
        answers.add(a71);
        answers.add(a72);
        answers.add(a73);
        answers.add(a74);
        answers.add(a75);
        answers.add(a76);
        answers.add(a77);
        answers.add(a78);
        answers.add(a79);
        answers.add(a80);
        answers.add(a81);
        answers.add(a82);
        answers.add(a83);
        answers.add(a84);
        answers.add(a85);
        answers.add(a86);
        answers.add(a87);
        answers.add(a88);
        answers.add(a89);
        answers.add(a90);
        answers.add(a91);
        answers.add(a92);
        answers.add(a93);
        answers.add(a94);
        answers.add(a95);
        answers.add(a96);
        answers.add(a97);
        answers.add(a98);
        answers.add(a99);
        answers.add(a100);
        answers.add(a101);
        answers.add(a102);
        answers.add(a103);
        answers.add(a104);
        answers.add(a105);
        answers.add(a106);
        answers.add(a107);
        answers.add(a108);
        answers.add(a109);
        answers.add(a110);
        answers.add(a111);
        answers.add(a112);
        return answers;
    }
    public static List<String[]>  initDate_XZ(Context mContext){
        List<String[]> answers = new ArrayList<>();
        String[] a1 = mContext.getResources().getStringArray(R.array.as_xz_1);
        String[] a2 = mContext.getResources().getStringArray(R.array.as_xz_2);
        String[] a3 = mContext.getResources().getStringArray(R.array.as_xz_3);
        String[] a4 = mContext.getResources().getStringArray(R.array.as_xz_4);
        String[] a5 = mContext.getResources().getStringArray(R.array.as_xz_5);
        String[] a6 = mContext.getResources().getStringArray(R.array.as_xz_6);
        String[] a7 = mContext.getResources().getStringArray(R.array.as_xz_7);
        String[] a8 = mContext.getResources().getStringArray(R.array.as_xz_8);
        String[] a9 = mContext.getResources().getStringArray(R.array.as_xz_9);
        String[] a10 = mContext.getResources().getStringArray(R.array.as_xz_10);
        String[] a11 = mContext.getResources().getStringArray(R.array.as_xz_11);
        String[] a12 = mContext.getResources().getStringArray(R.array.as_xz_12);
        String[] a13 = mContext.getResources().getStringArray(R.array.as_xz_13);
        String[] a14 = mContext.getResources().getStringArray(R.array.as_xz_14);
        String[] a15 = mContext.getResources().getStringArray(R.array.as_xz_15);
        String[] a16 = mContext.getResources().getStringArray(R.array.as_xz_16);
        String[] a17 = mContext.getResources().getStringArray(R.array.as_xz_17);
        String[] a18 = mContext.getResources().getStringArray(R.array.as_xz_18);
        String[] a19 = mContext.getResources().getStringArray(R.array.as_xz_19);
        String[] a20 = mContext.getResources().getStringArray(R.array.as_xz_20);
        String[] a21 = mContext.getResources().getStringArray(R.array.as_xz_21);
        String[] a22 = mContext.getResources().getStringArray(R.array.as_xz_22);
        String[] a23 = mContext.getResources().getStringArray(R.array.as_xz_23);
        String[] a24 = mContext.getResources().getStringArray(R.array.as_xz_24);
        String[] a25 = mContext.getResources().getStringArray(R.array.as_xz_25);
        String[] a26 = mContext.getResources().getStringArray(R.array.as_xz_26);
        String[] a27 = mContext.getResources().getStringArray(R.array.as_xz_27);
        String[] a28 = mContext.getResources().getStringArray(R.array.as_xz_28);
        String[] a29 = mContext.getResources().getStringArray(R.array.as_xz_29);
        String[] a30 = mContext.getResources().getStringArray(R.array.as_xz_30);
        String[] a31 = mContext.getResources().getStringArray(R.array.as_xz_31);
        String[] a32 = mContext.getResources().getStringArray(R.array.as_xz_32);
        String[] a33 = mContext.getResources().getStringArray(R.array.as_xz_33);
        String[] a34 = mContext.getResources().getStringArray(R.array.as_xz_34);
        String[] a35 = mContext.getResources().getStringArray(R.array.as_xz_35);
        String[] a36 = mContext.getResources().getStringArray(R.array.as_xz_36);
        String[] a37 = mContext.getResources().getStringArray(R.array.as_xz_37);
        String[] a38 = mContext.getResources().getStringArray(R.array.as_xz_38);
        String[] a39 = mContext.getResources().getStringArray(R.array.as_xz_39);
        String[] a40 = mContext.getResources().getStringArray(R.array.as_xz_40);
        String[] a41 = mContext.getResources().getStringArray(R.array.as_xz_41);
        String[] a42 = mContext.getResources().getStringArray(R.array.as_xz_42);
        String[] a43 = mContext.getResources().getStringArray(R.array.as_xz_43);
        String[] a44 = mContext.getResources().getStringArray(R.array.as_xz_44);
        String[] a45 = mContext.getResources().getStringArray(R.array.as_xz_45);
        String[] a46 = mContext.getResources().getStringArray(R.array.as_xz_46);
        String[] a47 = mContext.getResources().getStringArray(R.array.as_xz_47);
        String[] a48 = mContext.getResources().getStringArray(R.array.as_xz_48);
        String[] a49 = mContext.getResources().getStringArray(R.array.as_xz_49);
        String[] a50 = mContext.getResources().getStringArray(R.array.as_xz_50);
        answers.add(a1);
        answers.add(a2);
        answers.add(a3);
        answers.add(a4);
        answers.add(a5);
        answers.add(a6);
        answers.add(a7);
        answers.add(a8);
        answers.add(a9);
        answers.add(a10);
        answers.add(a11);
        answers.add(a12);
        answers.add(a13);
        answers.add(a14);
        answers.add(a15);
        answers.add(a16);
        answers.add(a17);
        answers.add(a18);
        answers.add(a19);
        answers.add(a20);
        answers.add(a21);
        answers.add(a22);
        answers.add(a23);
        answers.add(a24);
        answers.add(a25);
        answers.add(a26);
        answers.add(a27);
        answers.add(a28);
        answers.add(a29);
        answers.add(a30);
        answers.add(a31);
        answers.add(a32);
        answers.add(a33);
        answers.add(a34);
        answers.add(a35);
        answers.add(a36);
        answers.add(a37);
        answers.add(a38);
        answers.add(a39);
        answers.add(a40);
        answers.add(a41);
        answers.add(a42);
        answers.add(a43);
        answers.add(a44);
        answers.add(a45);
        answers.add(a46);
        answers.add(a47);
        answers.add(a48);
        answers.add(a49);
        answers.add(a50);
        return answers;
    }
    public static List<String[]> initDate_SFY(Context mContext){
        List<String[]> answers = new ArrayList<>();
        String[] a1 = mContext.getResources().getStringArray(R.array.as_s_1);
        String[] a2 = mContext.getResources().getStringArray(R.array.as_s_2);
        String[] a3 = mContext.getResources().getStringArray(R.array.as_s_3);
        String[] a4 = mContext.getResources().getStringArray(R.array.as_s_4);
        String[] a5 = mContext.getResources().getStringArray(R.array.as_s_5);
        String[] a6 = mContext.getResources().getStringArray(R.array.as_s_6);
        String[] a7 = mContext.getResources().getStringArray(R.array.as_s_7);
        String[] a8 = mContext.getResources().getStringArray(R.array.as_s_8);
        String[] a9 = mContext.getResources().getStringArray(R.array.as_s_9);
        String[] a10 = mContext.getResources().getStringArray(R.array.as_s_10);
        String[] a11 = mContext.getResources().getStringArray(R.array.as_s_11);
        String[] a12 = mContext.getResources().getStringArray(R.array.as_s_12);
        String[] a13 = mContext.getResources().getStringArray(R.array.as_s_13);
        String[] a14 = mContext.getResources().getStringArray(R.array.as_s_14);
        String[] a15 = mContext.getResources().getStringArray(R.array.as_s_15);
        String[] a16 = mContext.getResources().getStringArray(R.array.as_s_16);
        String[] a17 = mContext.getResources().getStringArray(R.array.as_s_17);
        String[] a18 = mContext.getResources().getStringArray(R.array.as_s_18);
        String[] a19 = mContext.getResources().getStringArray(R.array.as_s_19);
        String[] a20 = mContext.getResources().getStringArray(R.array.as_s_20);
        String[] a21 = mContext.getResources().getStringArray(R.array.as_s_21);
        String[] a22 = mContext.getResources().getStringArray(R.array.as_s_22);
        String[] a23 = mContext.getResources().getStringArray(R.array.as_s_23);
        String[] a24 = mContext.getResources().getStringArray(R.array.as_s_24);
        String[] a25 = mContext.getResources().getStringArray(R.array.as_s_25);
        String[] a26 = mContext.getResources().getStringArray(R.array.as_s_26);
        String[] a27 = mContext.getResources().getStringArray(R.array.as_s_27);
        String[] a28 = mContext.getResources().getStringArray(R.array.as_s_28);
        String[] a29 = mContext.getResources().getStringArray(R.array.as_s_29);
        String[] a30 = mContext.getResources().getStringArray(R.array.as_s_30);
        String[] a31 = mContext.getResources().getStringArray(R.array.as_s_31);
        String[] a32 = mContext.getResources().getStringArray(R.array.as_s_32);
        String[] a33 = mContext.getResources().getStringArray(R.array.as_s_33);
        String[] a34 = mContext.getResources().getStringArray(R.array.as_s_34);
        String[] a35 = mContext.getResources().getStringArray(R.array.as_s_35);
        String[] a36 = mContext.getResources().getStringArray(R.array.as_s_36);
        String[] a37 = mContext.getResources().getStringArray(R.array.as_s_37);
        String[] a38 = mContext.getResources().getStringArray(R.array.as_s_38);
        String[] a39 = mContext.getResources().getStringArray(R.array.as_s_39);
        String[] a40 = mContext.getResources().getStringArray(R.array.as_s_40);
        String[] a41 = mContext.getResources().getStringArray(R.array.as_s_41);
        String[] a42 = mContext.getResources().getStringArray(R.array.as_s_42);
        String[] a43 = mContext.getResources().getStringArray(R.array.as_s_43);
        String[] a44 = mContext.getResources().getStringArray(R.array.as_s_44);
        String[] a45 = mContext.getResources().getStringArray(R.array.as_s_45);
        String[] a46 = mContext.getResources().getStringArray(R.array.as_s_46);
        String[] a47 = mContext.getResources().getStringArray(R.array.as_s_47);
        String[] a48 = mContext.getResources().getStringArray(R.array.as_s_48);
        String[] a49 = mContext.getResources().getStringArray(R.array.as_s_49);
        String[] a50 = mContext.getResources().getStringArray(R.array.as_s_50);
        String[] a51 = mContext.getResources().getStringArray(R.array.as_s_51);
        String[] a52 = mContext.getResources().getStringArray(R.array.as_s_52);
        String[] a53 = mContext.getResources().getStringArray(R.array.as_s_53);
        String[] a54 = mContext.getResources().getStringArray(R.array.as_s_54);
        String[] a55 = mContext.getResources().getStringArray(R.array.as_s_55);
        String[] a56 = mContext.getResources().getStringArray(R.array.as_s_56);
        String[] a57 = mContext.getResources().getStringArray(R.array.as_s_57);
        String[] a58 = mContext.getResources().getStringArray(R.array.as_s_58);
        String[] a59 = mContext.getResources().getStringArray(R.array.as_s_59);
        String[] a60 = mContext.getResources().getStringArray(R.array.as_s_60);
        String[] a61 = mContext.getResources().getStringArray(R.array.as_s_61);
        String[] a62 = mContext.getResources().getStringArray(R.array.as_s_62);
        String[] a63 = mContext.getResources().getStringArray(R.array.as_s_63);
        String[] a64 = mContext.getResources().getStringArray(R.array.as_s_64);
        String[] a65 = mContext.getResources().getStringArray(R.array.as_s_65);
        String[] a66 = mContext.getResources().getStringArray(R.array.as_s_66);
        String[] a67 = mContext.getResources().getStringArray(R.array.as_s_67);
        String[] a68 = mContext.getResources().getStringArray(R.array.as_s_68);
        String[] a69 = mContext.getResources().getStringArray(R.array.as_s_69);
        String[] a70 = mContext.getResources().getStringArray(R.array.as_s_70);
        String[] a71 = mContext.getResources().getStringArray(R.array.as_s_71);
        String[] a72 = mContext.getResources().getStringArray(R.array.as_s_72);
        String[] a73 = mContext.getResources().getStringArray(R.array.as_s_73);
        String[] a74 = mContext.getResources().getStringArray(R.array.as_s_74);
        String[] a75 = mContext.getResources().getStringArray(R.array.as_s_75);
        String[] a76 = mContext.getResources().getStringArray(R.array.as_s_76);
        String[] a77 = mContext.getResources().getStringArray(R.array.as_s_77);
        String[] a78 = mContext.getResources().getStringArray(R.array.as_s_78);
        String[] a79 = mContext.getResources().getStringArray(R.array.as_s_79);
        String[] a80 = mContext.getResources().getStringArray(R.array.as_s_80);
        String[] a81 = mContext.getResources().getStringArray(R.array.as_s_81);
        String[] a82 = mContext.getResources().getStringArray(R.array.as_s_82);
        String[] a83 = mContext.getResources().getStringArray(R.array.as_s_83);
        String[] a84 = mContext.getResources().getStringArray(R.array.as_s_84);
        String[] a85 = mContext.getResources().getStringArray(R.array.as_s_85);
        String[] a86 = mContext.getResources().getStringArray(R.array.as_s_86);
        String[] a87 = mContext.getResources().getStringArray(R.array.as_s_87);
        String[] a88 = mContext.getResources().getStringArray(R.array.as_s_88);
        String[] a89 = mContext.getResources().getStringArray(R.array.as_s_89);
        String[] a90 = mContext.getResources().getStringArray(R.array.as_s_90);
        String[] a91 = mContext.getResources().getStringArray(R.array.as_s_91);
        String[] a92 = mContext.getResources().getStringArray(R.array.as_s_92);
        String[] a93 = mContext.getResources().getStringArray(R.array.as_s_93);
        String[] a94 = mContext.getResources().getStringArray(R.array.as_s_94);
        String[] a95 = mContext.getResources().getStringArray(R.array.as_s_95);
        String[] a96 = mContext.getResources().getStringArray(R.array.as_s_96);
        String[] a97 = mContext.getResources().getStringArray(R.array.as_s_97);
        String[] a98 = mContext.getResources().getStringArray(R.array.as_s_98);
        String[] a99 = mContext.getResources().getStringArray(R.array.as_s_99);
        String[] a100 = mContext.getResources().getStringArray(R.array.as_s_100);
        String[] a101 = mContext.getResources().getStringArray(R.array.as_s_101);
        String[] a102 = mContext.getResources().getStringArray(R.array.as_s_102);
        String[] a103 = mContext.getResources().getStringArray(R.array.as_s_103);
        String[] a104 = mContext.getResources().getStringArray(R.array.as_s_104);
        String[] a105 = mContext.getResources().getStringArray(R.array.as_s_105);
        String[] a106 = mContext.getResources().getStringArray(R.array.as_s_106);
        String[] a107 = mContext.getResources().getStringArray(R.array.as_s_107);
        String[] a108 = mContext.getResources().getStringArray(R.array.as_s_108);
        String[] a109 = mContext.getResources().getStringArray(R.array.as_s_109);
        String[] a110 = mContext.getResources().getStringArray(R.array.as_s_110);
        String[] a111 = mContext.getResources().getStringArray(R.array.as_s_111);
        String[] a112 = mContext.getResources().getStringArray(R.array.as_s_112);
        String[] a113 = mContext.getResources().getStringArray(R.array.as_s_113);
        String[] a114 = mContext.getResources().getStringArray(R.array.as_s_114);
        String[] a115 = mContext.getResources().getStringArray(R.array.as_s_115);
        String[] a116 = mContext.getResources().getStringArray(R.array.as_s_116);
        String[] a117 = mContext.getResources().getStringArray(R.array.as_s_117);
        String[] a118 = mContext.getResources().getStringArray(R.array.as_s_118);
        String[] a119 = mContext.getResources().getStringArray(R.array.as_s_119);
        String[] a120 = mContext.getResources().getStringArray(R.array.as_s_120);
        String[] a121 = mContext.getResources().getStringArray(R.array.as_s_121);
        String[] a122 = mContext.getResources().getStringArray(R.array.as_s_122);
        String[] a123 = mContext.getResources().getStringArray(R.array.as_s_123);
        String[] a124 = mContext.getResources().getStringArray(R.array.as_s_124);
        String[] a125 = mContext.getResources().getStringArray(R.array.as_s_125);
        String[] a126 = mContext.getResources().getStringArray(R.array.as_s_126);
        String[] a127 = mContext.getResources().getStringArray(R.array.as_s_127);
        String[] a128 = mContext.getResources().getStringArray(R.array.as_s_128);
        String[] a129 = mContext.getResources().getStringArray(R.array.as_s_129);
        String[] a130 = mContext.getResources().getStringArray(R.array.as_s_130);
        String[] a131 = mContext.getResources().getStringArray(R.array.as_s_131);
        String[] a132 = mContext.getResources().getStringArray(R.array.as_s_132);
        String[] a133 = mContext.getResources().getStringArray(R.array.as_s_133);
        String[] a134 = mContext.getResources().getStringArray(R.array.as_s_134);
        String[] a135 = mContext.getResources().getStringArray(R.array.as_s_135);
        String[] a136 = mContext.getResources().getStringArray(R.array.as_s_136);
        String[] a137 = mContext.getResources().getStringArray(R.array.as_s_137);
        String[] a138 = mContext.getResources().getStringArray(R.array.as_s_138);
        String[] a139 = mContext.getResources().getStringArray(R.array.as_s_139);
        String[] a140 = mContext.getResources().getStringArray(R.array.as_s_140);
        String[] a141 = mContext.getResources().getStringArray(R.array.as_s_141);
        answers.add(a1);
        answers.add(a2);
        answers.add(a3);
        answers.add(a4);
        answers.add(a5);
        answers.add(a6);
        answers.add(a7);
        answers.add(a8);
        answers.add(a9);
        answers.add(a10);
        answers.add(a11);
        answers.add(a12);
        answers.add(a13);
        answers.add(a14);
        answers.add(a15);
        answers.add(a16);
        answers.add(a17);
        answers.add(a18);
        answers.add(a19);
        answers.add(a20);
        answers.add(a21);
        answers.add(a22);
        answers.add(a23);
        answers.add(a24);
        answers.add(a25);
        answers.add(a26);
        answers.add(a27);
        answers.add(a28);
        answers.add(a29);
        answers.add(a30);
        answers.add(a31);
        answers.add(a32);
        answers.add(a33);
        answers.add(a34);
        answers.add(a35);
        answers.add(a36);
        answers.add(a37);
        answers.add(a38);
        answers.add(a39);
        answers.add(a40);
        answers.add(a41);
        answers.add(a42);
        answers.add(a43);
        answers.add(a44);
        answers.add(a45);
        answers.add(a46);
        answers.add(a47);
        answers.add(a48);
        answers.add(a49);
        answers.add(a50);
        answers.add(a51);
        answers.add(a52);
        answers.add(a53);
        answers.add(a54);
        answers.add(a55);
        answers.add(a56);
        answers.add(a57);
        answers.add(a58);
        answers.add(a59);
        answers.add(a60);
        answers.add(a61);
        answers.add(a62);
        answers.add(a63);
        answers.add(a64);
        answers.add(a65);
        answers.add(a66);
        answers.add(a67);
        answers.add(a68);
        answers.add(a69);
        answers.add(a70);
        answers.add(a71);
        answers.add(a72);
        answers.add(a73);
        answers.add(a74);
        answers.add(a75);
        answers.add(a76);
        answers.add(a77);
        answers.add(a78);
        answers.add(a79);
        answers.add(a80);
        answers.add(a81);
        answers.add(a82);
        answers.add(a83);
        answers.add(a84);
        answers.add(a85);
        answers.add(a86);
        answers.add(a87);
        answers.add(a88);
        answers.add(a89);
        answers.add(a90);
        answers.add(a91);
        answers.add(a92);
        answers.add(a93);
        answers.add(a94);
        answers.add(a95);
        answers.add(a96);
        answers.add(a97);
        answers.add(a98);
        answers.add(a99);
        answers.add(a100);
        answers.add(a101);
        answers.add(a102);
        answers.add(a103);
        answers.add(a104);
        answers.add(a105);
        answers.add(a106);
        answers.add(a107);
        answers.add(a108);
        answers.add(a109);
        answers.add(a110);
        answers.add(a111);
        answers.add(a112);
        answers.add(a113);
        answers.add(a114);
        answers.add(a115);
        answers.add(a116);
        answers.add(a117);
        answers.add(a118);
        answers.add(a119);
        answers.add(a120);
        answers.add(a121);
        answers.add(a122);
        answers.add(a123);
        answers.add(a124);
        answers.add(a125);
        answers.add(a126);
        answers.add(a127);
        answers.add(a128);
        answers.add(a129);
        answers.add(a130);
        answers.add(a131);
        answers.add(a132);
        answers.add(a133);
        answers.add(a134);
        answers.add(a135);
        answers.add(a136);
        answers.add(a137);
        answers.add(a138);
        answers.add(a139);
        answers.add(a140);
        answers.add(a141);
        return answers;
    }
    public static List<String[]> initDate_SX(Context mContext){
        List<String[]> answers = new ArrayList<>();
        String[] a1 = mContext.getResources().getStringArray(R.array.as_sx_1);
        String[] a2 = mContext.getResources().getStringArray(R.array.as_sx_2);
        String[] a3 = mContext.getResources().getStringArray(R.array.as_sx_3);
        String[] a4 = mContext.getResources().getStringArray(R.array.as_sx_4);
        String[] a5 = mContext.getResources().getStringArray(R.array.as_sx_5);
        String[] a6 = mContext.getResources().getStringArray(R.array.as_sx_6);
        String[] a7 = mContext.getResources().getStringArray(R.array.as_sx_7);
        String[] a8 = mContext.getResources().getStringArray(R.array.as_sx_8);
        String[] a9 = mContext.getResources().getStringArray(R.array.as_sx_9);
        String[] a10 = mContext.getResources().getStringArray(R.array.as_sx_10);
        String[] a11 = mContext.getResources().getStringArray(R.array.as_sx_11);
        String[] a12 = mContext.getResources().getStringArray(R.array.as_sx_12);
        String[] a13 = mContext.getResources().getStringArray(R.array.as_sx_13);
        String[] a14 = mContext.getResources().getStringArray(R.array.as_sx_14);
        String[] a15 = mContext.getResources().getStringArray(R.array.as_sx_15);
        String[] a16 = mContext.getResources().getStringArray(R.array.as_sx_16);
        String[] a17 = mContext.getResources().getStringArray(R.array.as_sx_17);
        String[] a18 = mContext.getResources().getStringArray(R.array.as_sx_18);
        String[] a19 = mContext.getResources().getStringArray(R.array.as_sx_19);
        String[] a20 = mContext.getResources().getStringArray(R.array.as_sx_20);
        String[] a21 = mContext.getResources().getStringArray(R.array.as_sx_21);
        String[] a22 = mContext.getResources().getStringArray(R.array.as_sx_22);
        String[] a23 = mContext.getResources().getStringArray(R.array.as_sx_23);
        String[] a24 = mContext.getResources().getStringArray(R.array.as_sx_24);
        String[] a25 = mContext.getResources().getStringArray(R.array.as_sx_25);
        String[] a26 = mContext.getResources().getStringArray(R.array.as_sx_26);
        String[] a27 = mContext.getResources().getStringArray(R.array.as_sx_27);
        String[] a28 = mContext.getResources().getStringArray(R.array.as_sx_28);
        String[] a29 = mContext.getResources().getStringArray(R.array.as_sx_29);
        String[] a30 = mContext.getResources().getStringArray(R.array.as_sx_30);
        String[] a31 = mContext.getResources().getStringArray(R.array.as_sx_31);
        String[] a32 = mContext.getResources().getStringArray(R.array.as_sx_32);
        String[] a33 = mContext.getResources().getStringArray(R.array.as_sx_33);
        String[] a34 = mContext.getResources().getStringArray(R.array.as_sx_34);
        String[] a35 = mContext.getResources().getStringArray(R.array.as_sx_35);
        String[] a36 = mContext.getResources().getStringArray(R.array.as_sx_36);
        String[] a37 = mContext.getResources().getStringArray(R.array.as_sx_37);
        String[] a38 = mContext.getResources().getStringArray(R.array.as_sx_38);
        String[] a39 = mContext.getResources().getStringArray(R.array.as_sx_39);
        String[] a40 = mContext.getResources().getStringArray(R.array.as_sx_40);
        String[] a41 = mContext.getResources().getStringArray(R.array.as_sx_41);
        String[] a42 = mContext.getResources().getStringArray(R.array.as_sx_42);
        String[] a43 = mContext.getResources().getStringArray(R.array.as_sx_43);
        String[] a44 = mContext.getResources().getStringArray(R.array.as_sx_44);
        String[] a45 = mContext.getResources().getStringArray(R.array.as_sx_45);
        String[] a46 = mContext.getResources().getStringArray(R.array.as_sx_46);
        String[] a47 = mContext.getResources().getStringArray(R.array.as_sx_47);
        String[] a48 = mContext.getResources().getStringArray(R.array.as_sx_48);
        String[] a49 = mContext.getResources().getStringArray(R.array.as_sx_49);
        String[] a50 = mContext.getResources().getStringArray(R.array.as_sx_50);
        String[] a51 = mContext.getResources().getStringArray(R.array.as_sx_51);
        String[] a52 = mContext.getResources().getStringArray(R.array.as_sx_52);
        String[] a53 = mContext.getResources().getStringArray(R.array.as_sx_53);
        String[] a54 = mContext.getResources().getStringArray(R.array.as_sx_54);
        String[] a55 = mContext.getResources().getStringArray(R.array.as_sx_55);
        String[] a56 = mContext.getResources().getStringArray(R.array.as_sx_56);
        String[] a57 = mContext.getResources().getStringArray(R.array.as_sx_57);
        String[] a58 = mContext.getResources().getStringArray(R.array.as_sx_58);
        String[] a59 = mContext.getResources().getStringArray(R.array.as_sx_59);
        String[] a60 = mContext.getResources().getStringArray(R.array.as_sx_60);
        String[] a61 = mContext.getResources().getStringArray(R.array.as_sx_61);
        String[] a62 = mContext.getResources().getStringArray(R.array.as_sx_62);
        String[] a63 = mContext.getResources().getStringArray(R.array.as_sx_63);
        String[] a64 = mContext.getResources().getStringArray(R.array.as_sx_64);
        String[] a65 = mContext.getResources().getStringArray(R.array.as_sx_65);
        String[] a66 = mContext.getResources().getStringArray(R.array.as_sx_66);
        String[] a67 = mContext.getResources().getStringArray(R.array.as_sx_67);
        String[] a68 = mContext.getResources().getStringArray(R.array.as_sx_68);
        String[] a69 = mContext.getResources().getStringArray(R.array.as_sx_69);
        String[] a70 = mContext.getResources().getStringArray(R.array.as_sx_70);
        String[] a71 = mContext.getResources().getStringArray(R.array.as_sx_71);
        String[] a72 = mContext.getResources().getStringArray(R.array.as_sx_72);
        String[] a73 = mContext.getResources().getStringArray(R.array.as_sx_73);
        String[] a74 = mContext.getResources().getStringArray(R.array.as_sx_74);
        String[] a75 = mContext.getResources().getStringArray(R.array.as_sx_75);
        String[] a76 = mContext.getResources().getStringArray(R.array.as_sx_76);
        String[] a77 = mContext.getResources().getStringArray(R.array.as_sx_77);
        String[] a78 = mContext.getResources().getStringArray(R.array.as_sx_78);
        String[] a79 = mContext.getResources().getStringArray(R.array.as_sx_79);
        String[] a80 = mContext.getResources().getStringArray(R.array.as_sx_80);
        String[] a81 = mContext.getResources().getStringArray(R.array.as_sx_81);
        String[] a82 = mContext.getResources().getStringArray(R.array.as_sx_82);
        String[] a83 = mContext.getResources().getStringArray(R.array.as_sx_83);
        String[] a84 = mContext.getResources().getStringArray(R.array.as_sx_84);
        String[] a85 = mContext.getResources().getStringArray(R.array.as_sx_85);
        String[] a86 = mContext.getResources().getStringArray(R.array.as_sx_86);
        String[] a87 = mContext.getResources().getStringArray(R.array.as_sx_87);
        String[] a88 = mContext.getResources().getStringArray(R.array.as_sx_88);
        String[] a89 = mContext.getResources().getStringArray(R.array.as_sx_89);
        String[] a90 = mContext.getResources().getStringArray(R.array.as_sx_90);
        String[] a91 = mContext.getResources().getStringArray(R.array.as_sx_91);
        String[] a92 = mContext.getResources().getStringArray(R.array.as_sx_92);
        answers.add(a1);
        answers.add(a2);
        answers.add(a3);
        answers.add(a4);
        answers.add(a5);
        answers.add(a6);
        answers.add(a7);
        answers.add(a8);
        answers.add(a9);
        answers.add(a10);
        answers.add(a11);
        answers.add(a12);
        answers.add(a13);
        answers.add(a14);
        answers.add(a15);
        answers.add(a16);
        answers.add(a17);
        answers.add(a18);
        answers.add(a19);
        answers.add(a20);
        answers.add(a21);
        answers.add(a22);
        answers.add(a23);
        answers.add(a24);
        answers.add(a25);
        answers.add(a26);
        answers.add(a27);
        answers.add(a28);
        answers.add(a29);
        answers.add(a30);
        answers.add(a31);
        answers.add(a32);
        answers.add(a33);
        answers.add(a34);
        answers.add(a35);
        answers.add(a36);
        answers.add(a37);
        answers.add(a38);
        answers.add(a39);
        answers.add(a40);
        answers.add(a41);
        answers.add(a42);
        answers.add(a43);
        answers.add(a44);
        answers.add(a45);
        answers.add(a46);
        answers.add(a47);
        answers.add(a48);
        answers.add(a49);
        answers.add(a50);
        answers.add(a51);
        answers.add(a52);
        answers.add(a53);
        answers.add(a54);
        answers.add(a55);
        answers.add(a56);
        answers.add(a57);
        answers.add(a58);
        answers.add(a59);
        answers.add(a60);
        answers.add(a61);
        answers.add(a62);
        answers.add(a63);
        answers.add(a64);
        answers.add(a65);
        answers.add(a66);
        answers.add(a67);
        answers.add(a68);
        answers.add(a69);
        answers.add(a70);
        answers.add(a71);
        answers.add(a72);
        answers.add(a73);
        answers.add(a74);
        answers.add(a75);
        answers.add(a76);
        answers.add(a77);
        answers.add(a78);
        answers.add(a79);
        answers.add(a80);
        answers.add(a81);
        answers.add(a82);
        answers.add(a83);
        answers.add(a84);
        answers.add(a85);
        answers.add(a86);
        answers.add(a87);
        answers.add(a88);
        answers.add(a89);
        answers.add(a90);
        answers.add(a91);
        answers.add(a92);
        return answers;
    }
    public static List<String[]>  initDate(Context mContext){
        List<String[]> answers = new ArrayList<>();
        String[] a1 = mContext.getResources().getStringArray(R.array.answers_1);
        String[] a2 = mContext.getResources().getStringArray(R.array.answers_2);
        String[] a3 = mContext.getResources().getStringArray(R.array.answers_3);
        String[] a4 = mContext.getResources().getStringArray(R.array.answers_4);
        String[] a5 = mContext.getResources().getStringArray(R.array.answers_5);
        String[] a6 = mContext.getResources().getStringArray(R.array.answers_6);
        String[] a7 = mContext.getResources().getStringArray(R.array.answers_7);
        String[] a8 = mContext.getResources().getStringArray(R.array.answers_8);
        String[] a9 = mContext.getResources().getStringArray(R.array.answers_9);
        String[] a10 = mContext.getResources().getStringArray(R.array.answers_10);
        String[] a11= mContext.getResources().getStringArray(R.array.answers_11);
        String[] a12 = mContext.getResources().getStringArray(R.array.answers_12);
        String[] a13 = mContext.getResources().getStringArray(R.array.answers_13);
        String[] a14 = mContext.getResources().getStringArray(R.array.answers_14);
        String[] a15 = mContext.getResources().getStringArray(R.array.answers_15);
        String[] a16 = mContext.getResources().getStringArray(R.array.answers_16);
        String[] a17 = mContext.getResources().getStringArray(R.array.answers_17);
        String[] a18 = mContext.getResources().getStringArray(R.array.answers_18);
        String[] a19 = mContext.getResources().getStringArray(R.array.answers_19);
        String[] a20 = mContext.getResources().getStringArray(R.array.answers_20);
        String[] a21 = mContext.getResources().getStringArray(R.array.answers_21);
        String[] a22 = mContext.getResources().getStringArray(R.array.answers_22);
        String[] a23 = mContext.getResources().getStringArray(R.array.answers_23);
        String[] a24 = mContext.getResources().getStringArray(R.array.answers_24);
        String[] a25 = mContext.getResources().getStringArray(R.array.answers_25);
        String[] a26 = mContext.getResources().getStringArray(R.array.answers_26);
        String[] a27 = mContext.getResources().getStringArray(R.array.answers_27);
        String[] a28 = mContext.getResources().getStringArray(R.array.answers_28);
        String[] a29 = mContext.getResources().getStringArray(R.array.answers_29);
        String[] a30 = mContext.getResources().getStringArray(R.array.answers_30);
        String[] a31 = mContext.getResources().getStringArray(R.array.answers_31);
        String[] a32 = mContext.getResources().getStringArray(R.array.answers_32);
        String[] a33 = mContext.getResources().getStringArray(R.array.answers_33);
        String[] a34 = mContext.getResources().getStringArray(R.array.answers_34);
        String[] a35 = mContext.getResources().getStringArray(R.array.answers_35);
        String[] a36 = mContext.getResources().getStringArray(R.array.answers_36);
        String[] a37 = mContext.getResources().getStringArray(R.array.answers_37);
        String[] a38 = mContext.getResources().getStringArray(R.array.answers_38);
        String[] a39 = mContext.getResources().getStringArray(R.array.answers_39);
        String[] a40 = mContext.getResources().getStringArray(R.array.answers_40);
        String[] a41 = mContext.getResources().getStringArray(R.array.answers_41);
        String[] a42 = mContext.getResources().getStringArray(R.array.answers_42);
        String[] a43 = mContext.getResources().getStringArray(R.array.answers_43);
        String[] a44 = mContext.getResources().getStringArray(R.array.answers_44);
        String[] a45 = mContext.getResources().getStringArray(R.array.answers_45);
        String[] a46 = mContext.getResources().getStringArray(R.array.answers_46);
        String[] a47 = mContext.getResources().getStringArray(R.array.answers_47);
        String[] a48 = mContext.getResources().getStringArray(R.array.answers_48);
        String[] a49 = mContext.getResources().getStringArray(R.array.answers_49);
        String[] a50 = mContext.getResources().getStringArray(R.array.answers_50);
        String[] a51 = mContext.getResources().getStringArray(R.array.answers_51);
        String[] a52 = mContext.getResources().getStringArray(R.array.answers_52);
        String[] a53 = mContext.getResources().getStringArray(R.array.answers_53);
        String[] a54 = mContext.getResources().getStringArray(R.array.answers_54);
        String[] a55 = mContext.getResources().getStringArray(R.array.answers_55);
        String[] a56 = mContext.getResources().getStringArray(R.array.answers_56);
        String[] a57 = mContext.getResources().getStringArray(R.array.answers_57);
        String[] a58 = mContext.getResources().getStringArray(R.array.answers_58);
        String[] a59 = mContext.getResources().getStringArray(R.array.answers_59);
        String[] a60 = mContext.getResources().getStringArray(R.array.answers_60);
        String[] a61 = mContext.getResources().getStringArray(R.array.answers_61);
        String[] a62 = mContext.getResources().getStringArray(R.array.answers_62);
        String[] a63 = mContext.getResources().getStringArray(R.array.answers_63);
        String[] a64= mContext.getResources().getStringArray(R.array.answers_64);
        String[] a65 = mContext.getResources().getStringArray(R.array.answers_65);
        String[] a66 = mContext.getResources().getStringArray(R.array.answers_66);
        String[] a67 = mContext.getResources().getStringArray(R.array.answers_67);
        String[] a68 = mContext.getResources().getStringArray(R.array.answers_68);
        String[] a69 = mContext.getResources().getStringArray(R.array.answers_69);
        String[] a70 = mContext.getResources().getStringArray(R.array.answers_70);
        String[] a71 = mContext.getResources().getStringArray(R.array.answers_71);
        String[] a72 = mContext.getResources().getStringArray(R.array.answers_72);
        String[] a73 = mContext.getResources().getStringArray(R.array.answers_73);
        String[] a74 = mContext.getResources().getStringArray(R.array.answers_74);
        String[] a75 = mContext.getResources().getStringArray(R.array.answers_75);
        String[] a76 = mContext.getResources().getStringArray(R.array.answers_76);
        String[] a77 = mContext.getResources().getStringArray(R.array.answers_77);
        String[] a78 = mContext.getResources().getStringArray(R.array.answers_78);
        String[] a79 = mContext.getResources().getStringArray(R.array.answers_79);
        String[] a80 = mContext.getResources().getStringArray(R.array.answers_80);
        String[] a81 = mContext.getResources().getStringArray(R.array.answers_81);
        String[] a82 = mContext.getResources().getStringArray(R.array.answers_82);
        String[] a83 = mContext.getResources().getStringArray(R.array.answers_83);
        String[] a84 = mContext.getResources().getStringArray(R.array.answers_84);
        String[] a85 = mContext.getResources().getStringArray(R.array.answers_85);
        String[] a86 = mContext.getResources().getStringArray(R.array.answers_86);
        String[] a87 = mContext.getResources().getStringArray(R.array.answers_87);
        String[] a88 = mContext.getResources().getStringArray(R.array.answers_88);
        String[] a89 = mContext.getResources().getStringArray(R.array.answers_89);
        String[] a90 = mContext.getResources().getStringArray(R.array.answers_90);
        String[] a91 = mContext.getResources().getStringArray(R.array.answers_91);
        String[] a92 = mContext.getResources().getStringArray(R.array.answers_92);
        String[] a93 = mContext.getResources().getStringArray(R.array.answers_93);
        String[] a94 = mContext.getResources().getStringArray(R.array.answers_94);
        String[] a95 = mContext.getResources().getStringArray(R.array.answers_95);
        String[] a96 = mContext.getResources().getStringArray(R.array.answers_96);
        String[] a97 = mContext.getResources().getStringArray(R.array.answers_97);
        String[] a98 = mContext.getResources().getStringArray(R.array.answers_98);
        String[] a99 = mContext.getResources().getStringArray(R.array.answers_99);
        String[] a100 = mContext.getResources().getStringArray(R.array.answers_100);
        String[] a101 = mContext.getResources().getStringArray(R.array.answers_101);
        String[] a102 = mContext.getResources().getStringArray(R.array.answers_102);
        String[] a103 = mContext.getResources().getStringArray(R.array.answers_103);
        String[] a104 = mContext.getResources().getStringArray(R.array.answers_104);
        String[] a105= mContext.getResources().getStringArray(R.array.answers_105);
        String[] a106 = mContext.getResources().getStringArray(R.array.answers_106);
        String[] a107 = mContext.getResources().getStringArray(R.array.answers_107);
        String[] a108 = mContext.getResources().getStringArray(R.array.answers_108);
        String[] a109 = mContext.getResources().getStringArray(R.array.answers_109);
        String[] a110 = mContext.getResources().getStringArray(R.array.answers_110);
        String[] a111 = mContext.getResources().getStringArray(R.array.answers_111);
        String[] a112 = mContext.getResources().getStringArray(R.array.answers_112);
        String[] a113 = mContext.getResources().getStringArray(R.array.answers_113);
        String[] a114 = mContext.getResources().getStringArray(R.array.answers_114);
        String[] a115 = mContext.getResources().getStringArray(R.array.answers_115);
        String[] a116 = mContext.getResources().getStringArray(R.array.answers_116);
        String[] a117 = mContext.getResources().getStringArray(R.array.answers_117);
        String[] a118 = mContext.getResources().getStringArray(R.array.answers_118);
        String[] a119 = mContext.getResources().getStringArray(R.array.answers_119);
        String[] a120 = mContext.getResources().getStringArray(R.array.answers_120);
        String[] a121 = mContext.getResources().getStringArray(R.array.answers_121);
        String[] a122 = mContext.getResources().getStringArray(R.array.answers_122);
        String[] a123 = mContext.getResources().getStringArray(R.array.answers_123);
        String[] a124 = mContext.getResources().getStringArray(R.array.answers_124);
        String[] a125 = mContext.getResources().getStringArray(R.array.answers_125);
        String[] a126 = mContext.getResources().getStringArray(R.array.answers_126);
        String[] a127 = mContext.getResources().getStringArray(R.array.answers_127);
        String[] a128 = mContext.getResources().getStringArray(R.array.answers_128);
        String[] a129 = mContext.getResources().getStringArray(R.array.answers_129);
        String[] a130 = mContext.getResources().getStringArray(R.array.answers_130);
        String[] a131 = mContext.getResources().getStringArray(R.array.answers_131);
        String[] a132 = mContext.getResources().getStringArray(R.array.answers_132);
        String[] a133 = mContext.getResources().getStringArray(R.array.answers_133);
        String[] a134 = mContext.getResources().getStringArray(R.array.answers_134);
        String[] a135 = mContext.getResources().getStringArray(R.array.answers_135);
        String[] a136 = mContext.getResources().getStringArray(R.array.answers_136);
        String[] a137 = mContext.getResources().getStringArray(R.array.answers_137);
        String[] a138 = mContext.getResources().getStringArray(R.array.answers_138);
        String[] a139 = mContext.getResources().getStringArray(R.array.answers_139);
        String[] a140 = mContext.getResources().getStringArray(R.array.answers_140);
        String[] a141 = mContext.getResources().getStringArray(R.array.answers_141);
        String[] a142 = mContext.getResources().getStringArray(R.array.answers_142);
        String[] a143 = mContext.getResources().getStringArray(R.array.answers_143);
        String[] a144 = mContext.getResources().getStringArray(R.array.answers_144);
        String[] a145 = mContext.getResources().getStringArray(R.array.answers_145);
        String[] a146 = mContext.getResources().getStringArray(R.array.answers_146);
        String[] a147 = mContext.getResources().getStringArray(R.array.answers_147);
        String[] a148 = mContext.getResources().getStringArray(R.array.answers_148);
        String[] a149 = mContext.getResources().getStringArray(R.array.answers_149);
        String[] a150 = mContext.getResources().getStringArray(R.array.answers_150);
        String[] a151 = mContext.getResources().getStringArray(R.array.answers_151);
        String[] a152 = mContext.getResources().getStringArray(R.array.answers_152);
        String[] a153 = mContext.getResources().getStringArray(R.array.answers_153);
        String[] a154 = mContext.getResources().getStringArray(R.array.answers_154);
        String[] a155 = mContext.getResources().getStringArray(R.array.answers_155);
        String[] a156 = mContext.getResources().getStringArray(R.array.answers_156);
        String[] a157 = mContext.getResources().getStringArray(R.array.answers_157);
        String[] a158 = mContext.getResources().getStringArray(R.array.answers_158);
        String[] a159 = mContext.getResources().getStringArray(R.array.answers_159);
        String[] a160 = mContext.getResources().getStringArray(R.array.answers_160);
        String[] a161 = mContext.getResources().getStringArray(R.array.answers_161);
        String[] a162 = mContext.getResources().getStringArray(R.array.answers_162);
        String[] a163 = mContext.getResources().getStringArray(R.array.answers_163);
        String[] a164 = mContext.getResources().getStringArray(R.array.answers_164);
        String[] a165 = mContext.getResources().getStringArray(R.array.answers_165);
        String[] a166 = mContext.getResources().getStringArray(R.array.answers_166);
        String[] a167 = mContext.getResources().getStringArray(R.array.answers_167);
        String[] a168 = mContext.getResources().getStringArray(R.array.answers_168);
        String[] a169 = mContext.getResources().getStringArray(R.array.answers_169);
        String[] a170 = mContext.getResources().getStringArray(R.array.answers_170);
        String[] a171 = mContext.getResources().getStringArray(R.array.answers_171);
        String[] a172 = mContext.getResources().getStringArray(R.array.answers_172);
        String[] a173 = mContext.getResources().getStringArray(R.array.answers_173);
        String[] a174 = mContext.getResources().getStringArray(R.array.answers_174);
        String[] a175 = mContext.getResources().getStringArray(R.array.answers_175);
        String[] a176 = mContext.getResources().getStringArray(R.array.answers_176);
        String[] a177 = mContext.getResources().getStringArray(R.array.answers_177);
        String[] a178 = mContext.getResources().getStringArray(R.array.answers_178);
        String[] a179 = mContext.getResources().getStringArray(R.array.answers_179);
        String[] a180 = mContext.getResources().getStringArray(R.array.answers_180);
        String[] a181 = mContext.getResources().getStringArray(R.array.answers_181);
        String[] a182 = mContext.getResources().getStringArray(R.array.answers_182);
        String[] a183 = mContext.getResources().getStringArray(R.array.answers_183);
        String[] a184 = mContext.getResources().getStringArray(R.array.answers_184);
        String[] a185 = mContext.getResources().getStringArray(R.array.answers_185);
        String[] a186 = mContext.getResources().getStringArray(R.array.answers_186);
        String[] a187 = mContext.getResources().getStringArray(R.array.answers_187);
        String[] a188 = mContext.getResources().getStringArray(R.array.answers_188);
        String[] a189 = mContext.getResources().getStringArray(R.array.answers_189);
        String[] a190 = mContext.getResources().getStringArray(R.array.answers_190);
        String[] a191 = mContext.getResources().getStringArray(R.array.answers_191);
        String[] a192 = mContext.getResources().getStringArray(R.array.answers_192);
        String[] a193 = mContext.getResources().getStringArray(R.array.answers_193);
        String[] a194 = mContext.getResources().getStringArray(R.array.answers_194);
        String[] a195 = mContext.getResources().getStringArray(R.array.answers_195);
        String[] a196 = mContext.getResources().getStringArray(R.array.answers_196);
        String[] a197 = mContext.getResources().getStringArray(R.array.answers_197);
        String[] a198 = mContext.getResources().getStringArray(R.array.answers_198);
        String[] a199 = mContext.getResources().getStringArray(R.array.answers_199);
        String[] a200 = mContext.getResources().getStringArray(R.array.answers_200);
        String[] a201 = mContext.getResources().getStringArray(R.array.answers_201);
        String[] a202 = mContext.getResources().getStringArray(R.array.answers_202);
        String[] a203 = mContext.getResources().getStringArray(R.array.answers_203);
        String[] a204 = mContext.getResources().getStringArray(R.array.answers_204);
        String[] a205 = mContext.getResources().getStringArray(R.array.answers_205);
        String[] a206 = mContext.getResources().getStringArray(R.array.answers_206);
        String[] a207 = mContext.getResources().getStringArray(R.array.answers_207);
        String[] a208 = mContext.getResources().getStringArray(R.array.answers_208);
        String[] a209 = mContext.getResources().getStringArray(R.array.answers_209);
        String[] a210 = mContext.getResources().getStringArray(R.array.answers_210);
        String[] a211 = mContext.getResources().getStringArray(R.array.answers_211);
        String[] a212 = mContext.getResources().getStringArray(R.array.answers_212);
        String[] a213 = mContext.getResources().getStringArray(R.array.answers_213);
        String[] a214 = mContext.getResources().getStringArray(R.array.answers_214);
        String[] a215 = mContext.getResources().getStringArray(R.array.answers_215);
        String[] a216 = mContext.getResources().getStringArray(R.array.answers_216);
        String[] a217 = mContext.getResources().getStringArray(R.array.answers_217);
        String[] a218 = mContext.getResources().getStringArray(R.array.answers_218);
        String[] a219 = mContext.getResources().getStringArray(R.array.answers_219);
        String[] a220 = mContext.getResources().getStringArray(R.array.answers_220);
        String[] a221 = mContext.getResources().getStringArray(R.array.answers_221);
        String[] a222 = mContext.getResources().getStringArray(R.array.answers_222);
        String[] a223 = mContext.getResources().getStringArray(R.array.answers_223);
        String[] a224 = mContext.getResources().getStringArray(R.array.answers_224);
        String[] a225 = mContext.getResources().getStringArray(R.array.answers_225);
        String[] a226 = mContext.getResources().getStringArray(R.array.answers_226);
        String[] a227 = mContext.getResources().getStringArray(R.array.answers_227);
        String[] a228 = mContext.getResources().getStringArray(R.array.answers_228);
        String[] a229 = mContext.getResources().getStringArray(R.array.answers_229);
        String[] a230 = mContext.getResources().getStringArray(R.array.answers_230);
        String[] a231 = mContext.getResources().getStringArray(R.array.answers_231);
        String[] a232= mContext.getResources().getStringArray(R.array.answers_232);
        String[] a233 = mContext.getResources().getStringArray(R.array.answers_233);
        String[] a234 = mContext.getResources().getStringArray(R.array.answers_234);
        String[] a235 = mContext.getResources().getStringArray(R.array.answers_235);
        String[] a236 = mContext.getResources().getStringArray(R.array.answers_236);
        String[] a237 = mContext.getResources().getStringArray(R.array.answers_237);
        String[] a238 = mContext.getResources().getStringArray(R.array.answers_238);
        String[] a239 = mContext.getResources().getStringArray(R.array.answers_239);
        String[] a240 = mContext.getResources().getStringArray(R.array.answers_240);
        String[] a241 = mContext.getResources().getStringArray(R.array.answers_241);
        String[] a242 = mContext.getResources().getStringArray(R.array.answers_242);
        String[] a243 = mContext.getResources().getStringArray(R.array.answers_243);
        String[] a244 = mContext.getResources().getStringArray(R.array.answers_244);
        String[] a245 = mContext.getResources().getStringArray(R.array.answers_245);
        String[] a246 = mContext.getResources().getStringArray(R.array.answers_246);
        String[] a247 = mContext.getResources().getStringArray(R.array.answers_247);
        String[] a248 = mContext.getResources().getStringArray(R.array.answers_248);
        String[] a249 = mContext.getResources().getStringArray(R.array.answers_249);
        String[] a250 = mContext.getResources().getStringArray(R.array.answers_250);
        String[] a251 = mContext.getResources().getStringArray(R.array.answers_251);
        String[] a252 = mContext.getResources().getStringArray(R.array.answers_252);
        String[] a253 = mContext.getResources().getStringArray(R.array.answers_253);
        String[] a254 = mContext.getResources().getStringArray(R.array.answers_254);
        String[] a255 = mContext.getResources().getStringArray(R.array.answers_255);
        String[] a256 = mContext.getResources().getStringArray(R.array.answers_256);
        String[] a257 = mContext.getResources().getStringArray(R.array.answers_257);
        String[] a258 = mContext.getResources().getStringArray(R.array.answers_258);
        String[] a259 = mContext.getResources().getStringArray(R.array.answers_259);
        String[] a260 = mContext.getResources().getStringArray(R.array.answers_260);
        String[] a261 = mContext.getResources().getStringArray(R.array.answers_261);
        String[] a262 = mContext.getResources().getStringArray(R.array.answers_262);
        String[] a263 = mContext.getResources().getStringArray(R.array.answers_263);
        String[] a264 = mContext.getResources().getStringArray(R.array.answers_264);
        String[] a265 = mContext.getResources().getStringArray(R.array.answers_265);
        String[] a266 = mContext.getResources().getStringArray(R.array.answers_266);
        String[] a267 = mContext.getResources().getStringArray(R.array.answers_267);

        answers.add(a1);
        answers.add(a2);
        answers.add(a3);
        answers.add(a4);
        answers.add(a5);
        answers.add(a6);
        answers.add(a7);
        answers.add(a8);
        answers.add(a9);
        answers.add(a10);
        answers.add(a11);
        answers.add(a12);
        answers.add(a13);
        answers.add(a14);
        answers.add(a15);
        answers.add(a16);
        answers.add(a17);
        answers.add(a18);
        answers.add(a19);
        answers.add(a20);
        answers.add(a21);
        answers.add(a22);
        answers.add(a23);
        answers.add(a24);
        answers.add(a25);
        answers.add(a26);
        answers.add(a27);
        answers.add(a28);
        answers.add(a29);
        answers.add(a30);
        answers.add(a31);
        answers.add(a32);
        answers.add(a33);
        answers.add(a34);
        answers.add(a35);
        answers.add(a36);
        answers.add(a37);
        answers.add(a38);
        answers.add(a39);
        answers.add(a40);
        answers.add(a41);
        answers.add(a42);
        answers.add(a43);
        answers.add(a44);
        answers.add(a45);
        answers.add(a46);
        answers.add(a47);
        answers.add(a48);
        answers.add(a49);
        answers.add(a50);
        answers.add(a51);
        answers.add(a52);
        answers.add(a53);
        answers.add(a54);
        answers.add(a55);
        answers.add(a56);
        answers.add(a57);
        answers.add(a58);
        answers.add(a59);
        answers.add(a60);
        answers.add(a61);
        answers.add(a62);
        answers.add(a63);
        answers.add(a64);
        answers.add(a65);
        answers.add(a66);
        answers.add(a67);
        answers.add(a68);
        answers.add(a69);
        answers.add(a70);
        answers.add(a71);
        answers.add(a72);
        answers.add(a73);
        answers.add(a74);
        answers.add(a75);
        answers.add(a76);
        answers.add(a77);
        answers.add(a78);
        answers.add(a79);
        answers.add(a80);
        answers.add(a81);
        answers.add(a82);
        answers.add(a83);
        answers.add(a84);
        answers.add(a85);
        answers.add(a86);
        answers.add(a87);
        answers.add(a88);
        answers.add(a89);
        answers.add(a90);
        answers.add(a91);
        answers.add(a92);
        answers.add(a93);
        answers.add(a94);
        answers.add(a95);
        answers.add(a96);
        answers.add(a97);
        answers.add(a98);
        answers.add(a99);
        answers.add(a100);
        answers.add(a101);
        answers.add(a102);
        answers.add(a103);
        answers.add(a104);
        answers.add(a105);
        answers.add(a106);
        answers.add(a107);
        answers.add(a108);
        answers.add(a109);
        answers.add(a110);
        answers.add(a111);
        answers.add(a112);
        answers.add(a113);
        answers.add(a114);
        answers.add(a115);
        answers.add(a116);
        answers.add(a117);
        answers.add(a118);
        answers.add(a119);
        answers.add(a120);
        answers.add(a121);
        answers.add(a122);
        answers.add(a123);
        answers.add(a124);
        answers.add(a125);
        answers.add(a126);
        answers.add(a127);
        answers.add(a128);
        answers.add(a129);
        answers.add(a130);
        answers.add(a131);
        answers.add(a132);
        answers.add(a133);
        answers.add(a134);
        answers.add(a135);
        answers.add(a136);
        answers.add(a137);
        answers.add(a138);
        answers.add(a139);
        answers.add(a140);
        answers.add(a141);
        answers.add(a142);
        answers.add(a143);
        answers.add(a144);
        answers.add(a145);
        answers.add(a146);
        answers.add(a147);
        answers.add(a148);
        answers.add(a149);
        answers.add(a150);
        answers.add(a151);
        answers.add(a152);
        answers.add(a153);
        answers.add(a154);
        answers.add(a155);
        answers.add(a156);
        answers.add(a157);
        answers.add(a158);
        answers.add(a159);
        answers.add(a160);
        answers.add(a161);
        answers.add(a162);
        answers.add(a163);
        answers.add(a164);
        answers.add(a165);
        answers.add(a166);
        answers.add(a167);
        answers.add(a168);
        answers.add(a169);
        answers.add(a170);
        answers.add(a171);
        answers.add(a172);
        answers.add(a173);
        answers.add(a174);
        answers.add(a175);
        answers.add(a176);
        answers.add(a177);
        answers.add(a178);
        answers.add(a179);
        answers.add(a180);
        answers.add(a181);
        answers.add(a182);
        answers.add(a183);
        answers.add(a184);
        answers.add(a185);
        answers.add(a186);
        answers.add(a187);
        answers.add(a188);
        answers.add(a189);
        answers.add(a190);
        answers.add(a191);
        answers.add(a192);
        answers.add(a193);
        answers.add(a194);
        answers.add(a195);
        answers.add(a196);
        answers.add(a197);
        answers.add(a198);
        answers.add(a199);
        answers.add(a200);
        answers.add(a201);
        answers.add(a202);
        answers.add(a203);
        answers.add(a204);
        answers.add(a205);
        answers.add(a206);
        answers.add(a207);
        answers.add(a208);
        answers.add(a209);
        answers.add(a210);
        answers.add(a211);
        answers.add(a212);
        answers.add(a213);
        answers.add(a214);
        answers.add(a215);
        answers.add(a216);
        answers.add(a217);
        answers.add(a218);
        answers.add(a219);
        answers.add(a220);
        answers.add(a221);
        answers.add(a222);
        answers.add(a223);
        answers.add(a224);
        answers.add(a225);
        answers.add(a226);
        answers.add(a227);
        answers.add(a228);
        answers.add(a229);
        answers.add(a230);
        answers.add(a231);
        answers.add(a232);
        answers.add(a233);
        answers.add(a234);
        answers.add(a235);
        answers.add(a236);
        answers.add(a237);
        answers.add(a238);
        answers.add(a239);
        answers.add(a240);
        answers.add(a241);
        answers.add(a242);
        answers.add(a243);
        answers.add(a244);
        answers.add(a245);
        answers.add(a246);
        answers.add(a247);
        answers.add(a248);
        answers.add(a249);
        answers.add(a250);
        answers.add(a251);
        answers.add(a252);
        answers.add(a253);
        answers.add(a254);
        answers.add(a255);
        answers.add(a256);
        answers.add(a257);
        answers.add(a258);
        answers.add(a259);
        answers.add(a260);
        answers.add(a261);
        answers.add(a262);
        answers.add(a263);
        answers.add(a264);
        answers.add(a265);
        answers.add(a266);
        answers.add(a267);
        return answers;
    }
}
